config/routes.rb
Rails.application.routes.draw do
  get '/start', to: 'repo#start', as: 'start'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repo.rb
class Repo < ApplicationRecord
  include HTTParty
  
  GITHUB_API = ENV["GITHUB_API"]
  
  def self.get_repos(page)
    response = HTTParty.get("https://api.github.com/users/learn-co-curriculum/repos?per_page=100&type=owner&page=#{page}&access_token=#{GITHUB_API}")
    if !!response && !!response[0]["name"]
      response.each do |repo|
        if repo["has_issues"] == true
          repository = self.find_or_create_by(name: repo["name"])
          repository.open_issues = repo["has_issues"]
          repository.pulls_url = repo["pulls_url"]
          binding.pry
          pull_response = HTTParty.get("https://api.github.com/users/learn-co-curriculum/repos?per_page=100&type=owner&page=#{page}&access_token=#{GITHUB_API}")
        end
      end
      self.get_repos(page + 1)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repo_controller.rb
class RepoController < ApplicationController
  
  def start 
    Repo.get_repos(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repo_helper.rb
module RepoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenIssuesFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repo/start.html.erb
<%= link_to "Get Repos", start_path %>

<script>
  
</script>